name: @NAME@
version: @VERSION@
main: com.tealcube.minecraft.spigot.metashop.MetaShopPlugin
depend: [Vault]

commands:
  metashop:
    aliases: [metas, mshop, ms]

permissions:
  metashop.command.show:
    default: op
  metashop.command.list:
    default: op
  metashop.command.select:
    default: op
  metashop.command.add:
    default: op
  metashop.command.remove:
    default: op